version: '3.7'

services:

  db_pagamentos:
    container_name: db_pagamentos
    image: postgres
    environment:
      - POSTGRES_DB=db_pagamentos
      - POSTGRES_USER=pagamentos
      - POSTGRES_PASSWORD=pagamentos
      - PGDATA=/data/postgres
    volumes:
      - ./db/pagamentos:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - dbs

  db_pedidos:
    container_name: db_pedidos
    image: postgres
    environment:
      - POSTGRES_DB=db_pedidos
      - POSTGRES_USER=pedidos
      - POSTGRES_PASSWORD=pedidos
      - PGDATA=/data/postgres
    volumes:
      - ./db/pedidos:/data/postgres
    ports:
      - "5431:5432"
    restart: always
    networks:
      - dbs

  ms-eureka:
    container_name: ms-eureka
    build: ./ms-eureka
    ports:
      - "8761:8761"
    networks:
      - mss
    restart: always
    
  ms-gateway:
    container_name: ms-gateway
    build: ./ms-gateway
    ports:
      - "80:80"
    networks:
      - mss
    restart: always
    depends_on:
      - ms-eureka

  ms-pagamentos:
    container_name: ms-pagamentos
    build: ./ms-pagamentos
    networks:
      - mss
      - dbs
    restart: always
    depends_on:
      - ms-eureka
      - db_pagamentos

  ms-pedidos:
    container_name: ms-pedidos
    build: ./ms-pedidos
    networks:
      - mss
      - dbs
    restart: always
    depends_on:
      - ms-eureka
      - db_pedidos


networks:
  mss:
    driver: bridge
  dbs:
    driver: bridge