version: '3.7'

services:

  db_pagamentos:
    container_name: db_pagamentos
    image: postgres
    environment:
      - POSTGRES_DB=db_pagamentos
      - POSTGRES_USER=pagamentos
      - POSTGRES_PASSWORD=pagamentos
      - PGDATA=/data/postgres
    volumes:
      - ./db/pagamentos:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - db

  db_pedidos:
    container_name: db_pedidos
    image: postgres
    environment:
      - POSTGRES_DB=db_pedidos
      - POSTGRES_USER=pedidos
      - POSTGRES_PASSWORD=pedidos
      - PGDATA=/data/postgres
    volumes:
      - ./db/pedidos:/data/postgres
    ports:
      - "5431:5432"
    restart: always
    networks:
      - db

networks:
  db:
    driver: bridge